### ISSUE TITLE
Package broken?

### ISSUE THREAD

**Issue by hadleyrich** [FusionAuth/fusionauth-python-client#1]
Hi,

This isn't a very useful issue sorry as I don't understand your build system, but, the package seems to be broken, both on PyPI and if I manually clone the repo and run setup.py

I managed to get it installing by moving the code around in src/ adjusting the setup.py and including requests as an install_requires but I didn't submit a pull request due to not understanding your larger build environment and guessing that would break it.

Cheers

**Comment by robotdan** [comment]
Hi @hadleyrich thanks for letting us know. I'm not a Python expert by any means. 

@tyduptyler13 can you help with this one?

**Comment by hadleyrich** [comment]
Just some debugging info to help out:

`[hads:~] 130 $ mkvirtualenv --python=/usr/bin/python3 tmp
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/hads/.virtualenvs/tmp/bin/python3
Also creating executable in /home/hads/.virtualenvs/tmp/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
[hads:~] [tmp] 5s $ pip install -v fusionauth-client
Created temporary directory: /tmp/pip-ephem-wheel-cache-ssf2me61
Created temporary directory: /tmp/pip-req-tracker-cmtt6ezp
Created requirements tracker '/tmp/pip-req-tracker-cmtt6ezp'
Created temporary directory: /tmp/pip-install-bpxrdljn
Collecting fusionauth-client
  1 location(s) to search for versions of fusionauth-client:
  * https://pypi.org/simple/fusionauth-client/
  Getting page https://pypi.org/simple/fusionauth-client/
  Looking up "https://pypi.org/simple/fusionauth-client/" in the cache
  Request header has "max_age" as 0, cache bypassed
  Starting new HTTPS connection (1): pypi.org:443
  https://pypi.org:443 "GET /simple/fusionauth-client/ HTTP/1.1" 304 0
  Analyzing links from page https://pypi.org/simple/fusionauth-client/
    Found link https://files.pythonhosted.org/packages/3c/3f/adcfef837e787dc7022c2527273af630a33e6c91cc6ff50836c1435c824d/fusionauth-client-1.0.17.tar.gz#sha256=d63c0d16606c97e4022a89d71141747d1be0cbd95969a855da01b1f0bfc9e0a4 (from https://pypi.org/simple/fusionauth-client/), version: 1.0.17
    Found link https://files.pythonhosted.org/packages/02/60/32ac76d54f98f74e07f6cee7c7bac6183d6bcdfd8aa7a96d72cb80ba1569/fusionauth_client-1.0.17-py3-none-any.whl#sha256=3931c0114eda2661c8c95da70984df7ef39bbd809515fb0fb37a05359a677fe8 (from https://pypi.org/simple/fusionauth-client/), version: 1.0.17
    Found link https://files.pythonhosted.org/packages/9e/61/c72aaa90dce78e92badd903604cf6740b2ff2e3838da5631e5ec10e00dd8/fusionauth-client-1.1.0.tar.gz#sha256=9b79bac61f610e34f52d7ddc0d09186a8dcb54a2d2182ab5ede0c573ae451573 (from https://pypi.org/simple/fusionauth-client/), version: 1.1.0
    Skipping link https://files.pythonhosted.org/packages/9d/82/55b68b11a216c4f161cdc5f4c713b6381d53482032d850e81eadd921bcdd/fusionauth_client-1.1.0-py2-none-any.whl#sha256=36f44651e00e539e1e721472e6d5e7bd48b8ae96815dcc30dc8fc657986b33c9 (from https://pypi.org/simple/fusionauth-client/); it is not compatible with this Python
    Found link https://files.pythonhosted.org/packages/c1/ef/17b32ce3cfbf50df8913dab89abec43e6cf75fdba35435c97fd613a47b9f/fusionauth-client-1.3.0.tar.gz#sha256=391c17e4acc2581397eaa6826740372de7c6839676a6510e6f332e586aea65a9 (from https://pypi.org/simple/fusionauth-client/), version: 1.3.0
    Skipping link https://files.pythonhosted.org/packages/f2/56/8854accc59f83a9a4861bf3f44952433d132387250d10a8ef1214da7b5f8/fusionauth_client-1.3.0-py2-none-any.whl#sha256=edb62a77619fd17082b5a80cdb96a37dacd138626da1cbb8ac2d9ad4949d1a3f (from https://pypi.org/simple/fusionauth-client/); it is not compatible with this Python
    Found link https://files.pythonhosted.org/packages/0e/16/4cde3f1d315d7fc9b697f7b22f5f5cd4d04e2349acd0dd0eb5e846e20460/fusionauth-client-1.4.0.tar.gz#sha256=d82db9bea59a15ad74aab9b81c594215ac1de89528d694dd4a56c6800758b4f4 (from https://pypi.org/simple/fusionauth-client/), version: 1.4.0
    Skipping link https://files.pythonhosted.org/packages/43/f6/d506498184518a4b6d11031b777652ebb470aa87053a2aef8c490b122c26/fusionauth_client-1.4.0-py2-none-any.whl#sha256=d0d5145ea95bf0838f79bb0b03bf8198ba10647001b4fe32e4c481f9445ebc7b (from https://pypi.org/simple/fusionauth-client/); it is not compatible with this Python
    Found link https://files.pythonhosted.org/packages/bb/d8/db916c752e840e9f6d565c5c4306abebadc2cd3aee88054c2a9241116075/fusionauth-client-1.5.0.tar.gz#sha256=c184e8869fa82e568f33f075919878d5384e9cc635b1e0015e4f3e2eebfdc485 (from https://pypi.org/simple/fusionauth-client/), version: 1.5.0
    Skipping link https://files.pythonhosted.org/packages/99/d1/f81f8fe6e7d7a91529200037dfb2e7259a80525fd331d7529fa5ae6f3f26/fusionauth_client-1.5.0-py2-none-any.whl#sha256=c5c114eb9bf12b2c0e2725ef52853972fba01adb340feec5025f1305cc1cc0f8 (from https://pypi.org/simple/fusionauth-client/); it is not compatible with this Python
    Found link https://files.pythonhosted.org/packages/d6/88/da201734fb5898beb0ec34cc4dd132296f3465da85768ea1979669ef2103/fusionauth-client-1.6.0.tar.gz#sha256=ad58eeedad3d4c29cb67ab7422702869e3857b81e65c798b928320cc9d6ed03a (from https://pypi.org/simple/fusionauth-client/), version: 1.6.0
    Skipping link https://files.pythonhosted.org/packages/1d/ec/40deaa5a1891cf2d07d2265cba3d192a764ea6b8986e5c855aef4a571c87/fusionauth_client-1.6.0-py2-none-any.whl#sha256=3e49ab633f0d3d43135fb83c2bf111be4b43a5c93cee76854bff3a52aebfc657 (from https://pypi.org/simple/fusionauth-client/); it is not compatible with this Python
  Using version 1.6.0 (newest of versions: 1.0.17, 1.1.0, 1.3.0, 1.4.0, 1.5.0, 1.6.0)
  Using cached wheel link: file:///home/hads/.cache/pip/wheels/2e/cf/52/342c1a26718c1a778bdc4c4701553782d217eb4b7e93f5a242/fusionauth_client-1.6.0-cp37-none-any.whl
  Added fusionauth-client from file:///home/hads/.cache/pip/wheels/2e/cf/52/342c1a26718c1a778bdc4c4701553782d217eb4b7e93f5a242/fusionauth_client-1.6.0-cp37-none-any.whl to build tracker '/tmp/pip-req-tracker-cmtt6ezp'
  Removed fusionauth-client from file:///home/hads/.cache/pip/wheels/2e/cf/52/342c1a26718c1a778bdc4c4701553782d217eb4b7e93f5a242/fusionauth_client-1.6.0-cp37-none-any.whl from build tracker '/tmp/pip-req-tracker-cmtt6ezp'
Installing collected packages: fusionauth-client

Successfully installed fusionauth-client-1.6.0
Cleaning up...
Removed build tracker '/tmp/pip-req-tracker-cmtt6ezp'
[hads:~] [tmp] $ unzip -l /home/hads/.cache/pip/wheels/2e/cf/52/342c1a26718c1a778bdc4c4701553782d217eb4b7e93f5a242/fusionauth_client-1.6.0-cp37-none-any.whl
Archive:  /home/hads/.cache/pip/wheels/2e/cf/52/342c1a26718c1a778bdc4c4701553782d217eb4b7e93f5a242/fusionauth_client-1.6.0-cp37-none-any.whl
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2018-10-29 19:31   src/__init__.py
     1793  2019-05-22 05:01   fusionauth_client-1.6.0.dist-info/METADATA
       93  2019-05-22 05:01   fusionauth_client-1.6.0.dist-info/WHEEL
        4  2019-05-22 05:01   fusionauth_client-1.6.0.dist-info/top_level.txt
      406  2019-05-22 05:01   fusionauth_client-1.6.0.dist-info/RECORD
---------                     -------
     2296                     5 files
[hads:~] [tmp] $ python
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from fusionauth.fusionauth_client import FusionAuthClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'fusionauth'
>>> 
`

**Comment by tyduptyler13** [comment]
Our automatic builds weren't publishing a python3 artifact. Moving forward we will only be publishing a python3 artifact as python2 is effectively deprecated.

You should be able to reinstall our dependency and it should work.

**Comment by hadleyrich** [comment]
Is there another step you need to complete? It's still not able to be installed either from PyPI or python setup.py install

**Comment by robotdan** [comment]
Hi @hadleyrich it looks like @tyduptyler13 may not have pushed the release to PyPI. 

Version 1.6.1 is now available via PyPI. https://pypi.org/project/fusionauth-client/

If that still isn't helping, we can take another look. Are you getting the same error that you posted earlier?

**Comment by hadleyrich** [comment]
Hey @robotdan Thanks for the quick response. Yup, still the same issue, more debugging below:

```
[hads:~] [tmp] 4s $ pip install fusionauth-client
Collecting fusionauth-client
  Downloading https://files.pythonhosted.org/packages/e5/19/1be7fcff5b3da4540b6073af0a7d8a0f520674a6347ba48bbec3b9723aaa/fusionauth_client-1.6.1-py3-none-any.whl
Installing collected packages: fusionauth-client
Successfully installed fusionauth-client-1.6.1
⌂81% [hads:~] [tmp] 3s $ python
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from fusionauth.fusionauth_client import FusionAuthClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'fusionauth'
>>> 
⌂71% [hads:~] [tmp] 12s $ wget https://files.pythonhosted.org/packages/e5/19/1be7fcff5b3da4540b6073af0a7d8a0f520674a6347ba48bbec3b9723aaa/fusionauth_client-1.6.1-py3-none-any.whl
--2019-05-27 16:16:23--  https://files.pythonhosted.org/packages/e5/19/1be7fcff5b3da4540b6073af0a7d8a0f520674a6347ba48bbec3b9723aaa/fusionauth_client-1.6.1-py3-none-any.whl
Resolving files.pythonhosted.org (files.pythonhosted.org)... 151.101.29.63, 2a04:4e42:7::319
Connecting to files.pythonhosted.org (files.pythonhosted.org)|151.101.29.63|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6189 (6.0K) [binary/octet-stream]
Saving to: ‘fusionauth_client-1.6.1-py3-none-any.whl’

fusionauth_client-1.6.1-py3-none-any.whl 100%[=================================================================================>]   6.04K  --.-KB/s    in 0.003s  

2019-05-27 16:16:23 (2.30 MB/s) - ‘fusionauth_client-1.6.1-py3-none-any.whl’ saved [6189/6189]

⌂69% [hads:~] [tmp] $ unzip -l fusionauth_client-1.6.1-py3-none-any.whl
Archive:  fusionauth_client-1.6.1-py3-none-any.whl
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2018-10-29 19:31   src/__init__.py
    11357  2019-05-27 04:11   fusionauth_client-1.6.1.dist-info/LICENSE
     1793  2019-05-27 04:11   fusionauth_client-1.6.1.dist-info/METADATA
       92  2019-05-27 04:11   fusionauth_client-1.6.1.dist-info/WHEEL
        4  2019-05-27 04:11   fusionauth_client-1.6.1.dist-info/top_level.txt
      505  2019-05-27 04:11   fusionauth_client-1.6.1.dist-info/RECORD
---------                     -------
    13751                     6 files
[hads:~] [tmp] $ 
```

**Comment by hadleyrich** [comment]
So there's actually no code packaged in there.

**Comment by tyduptyler13** [comment]
I adjusted our setup.py. The whl files now contain the code. Not sure how that was missed. I will let you know when the release is fixed.

**Comment by tyduptyler13** [comment]
One more followup. The setup.py was also missing our dependency on requests. Should be fixed now. (Will be fixed in 1.6.3)

**Comment by tyduptyler13** [comment]
If you remove and reinstall the package, it should be fixed now.

**Comment by hadleyrich** [comment]
Thanks very much @tyduptyler13 confirmed it's all golden now. Cheers!
