### ISSUE TITLE
Feature request: add search by ID to identity provider API

### ISSUE THREAD

**Issue by ypankovych** [FusionAuth/fusionauth-python-client#22]
Please add searching by ID to the identity provider API. 

Current workaround: adding the ID to provider name.

**Comment by mooreds** [comment]
Thanks for the feature request. 

The way we'd do this would be to add the API and a JSON file to this repository: https://github.com/fusionauth/fusionauth-client-builder

I added this tracking issue in our main GH issues repository: https://github.com/FusionAuth/fusionauth-issues/issues/2401

**Comment by robotdan** [comment]
We don't generally search by Id since this is unique. Instead we have a retrieve by Id. Is this what you're looking for?
- https://github.com/FusionAuth/fusionauth-python-client/blob/9722d8de6ef7c90e0683ac9ad39d37b5a8c00ace/src/main/python/fusionauth/fusionauth_client.py#L2546
