### ISSUE TITLE
Some endpoints missing

### ISSUE THREAD

**Issue by AliMirlou** [FusionAuth/fusionauth-python-client#8]
Hi,
I might have understood the protocols wrong but I was looking for the `introspect` endpoint in the client with no luck. Why is it and some other endpoints missing? Are they not needed in backends perhaps?

**Comment by robotdan** [comment]
It is not currently in the client libraries. We can look at adding it

**Comment by AliMirlou** [comment]
Isn't it an essential endpoint?

**Comment by mooreds** [comment]
Hiya,

You can definitely access it, just not through the client libraries. Here's some documentation about how to do so: https://fusionauth.io/docs/v1/tech/oauth/endpoints#introspect You can use a python HTTP library to create the POST request.

If you are only working with OAuth, you could also use any of the standard OAuth libraries. For this example app I used a mix of the FusionAuth client libraries and `requests_oauthlib`: https://github.com/FusionAuth/fusionauth-example-flask-portal

**Comment by robotdan** [comment]
I'm not against adding it to the client libs. 

See commits
https://github.com/FusionAuth/fusionauth-client-builder/commit/12569fdc46cba8f3f87c5498895696dac41bef23 and https://github.com/FusionAuth/fusionauth-python-client/commit/62fab4bbf9434572a63be1d47bec6978bc1d8ac3

I haven't tested this yet...  @AliMirlou feel free to see how it works. 

@mooreds or @AliMirlou any feedback on the method name?

**Comment by mooreds** [comment]
I'd probably call it `o_auth_introspect` for consistency (there are only a few other methods that reference oauth in the name, but one of them uses that clunky string).

**Comment by robotdan** [comment]
Yeah, normally we wouldn't mention `oauth2` but since this is a really specific method I didn't know what else to call it. 

I am fine with `o_auth_introspect` but it is (technically) an OAuth2 thing and not related to OAuth1 (I don't think anyway). But perhaps there is no confusion here since we don't support OAuth v1 at all.

**Comment by robotdan** [comment]
@AliMirlou any opinion on a name that suites the method, and is also "python-y" :-)

**Comment by AliMirlou** [comment]
@robotdan IMHO, I suggest `introspect_access_token` so that it can relate more to all the other method names like `exchange_o_auth_code_for_access_token` or `validate_device` which start with a verb.
All of the method names suggested in this issue are pythony though, so no comments on that. 😄

**Comment by robotdan** [comment]
I think we have a winner! `introspect_access_token` it is. Thanks for the feedback @AliMirlou .

**Comment by robotdan** [comment]
Available in master and 1.19.8 
https://pypi.org/project/fusionauth-client/
